# Generated by Django 3.0.5 on 2020-08-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadlogisticsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='EntryText',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
