# Generated by Django 3.0.5 on 2020-08-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadlogisticsApp', '0002_docket_entrytext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='DocketStatus',
            field=models.CharField(choices=[('1', 'Shipment Pickup From Origin'), ('2', 'Received At Origin Warehouse'), ('3', 'In Transit'), ('4', 'Received At Destination WareHouse'), ('5', 'Out For Delivery'), ('6', 'Delivered')], max_length=128),
        ),
    ]
