# Generated by Django 3.0.5 on 2020-08-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadlogisticsApp', '0003_auto_20200815_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='EntryText',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
