# Generated by Django 3.0.5 on 2020-08-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadlogisticsApp', '0004_auto_20200815_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='DocketStatus',
            field=models.CharField(choices=[('Shipment Pickup From Origin', 'Shipment Pickup From Origin'), ('Received At Origin Warehouse', 'Received At Origin Warehouse'), ('In Transit', 'In Transit'), ('Received At Destination WareHouse', 'Received At Destination WareHouse'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], max_length=128),
        ),
    ]
